import React from "react";
import Header from "./components/Header/Header";
import Nav from "./components/Nav/Nav";
import Main from "./components/Main/Main";
import Table from "./components/Main/Table/Table";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import "./App.scss";

function App() {

  const [menuState, setMenuState] = React.useState(false);

  function toggleMenu() {
    setMenuState(!menuState);
  }

  return (
    <>
      <Header toggleMenu={toggleMenu} />
      <Nav menuState={menuState} />
      <Main>
        <Table name="Live">
            
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
            <tr>
              <td>Denilson</td>
              <td>1000</td>
              <td>Dev</td>
            </tr>
        </Table>
      </Main>
    </>

    // <BrowserRouter>

    //   <Routes>

    //   </Routes>
    // </BrowserRouter>
  );
}

export default App;
